name: Lint and Format

on:
  push:
    paths:
      - '**/*.py'
      - 'pyproject.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-format:
    name: Ruff lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Ruff
        uses: astral-sh/setup-ruff@v3
        with:
          args: --version

      - name: Enforce lint
        id: ruff-lint
        run: ruff check --output-format=github .

      - name: Enforce format
        run: |
          ruff format --diff .
